apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-research
  namespace: argocd
spec:
  description: Team Research applications and environments
  sourceRepos:
    - https://github.com/CristianHz/gitops-config.git
  destinations:
    - namespace: team-research-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
