apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-infra
  namespace: argocd
spec:
  generators:
    - list:
        elements: []
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: platform-infra
      source:
        repoURL: https://github.com/CristianHz/gitops-config.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

# To activate, replace elements: [] with entries like:
# elements:
#   - name: infra-ingress-nginx
#     path: infra/shared/ingress-nginx
#     namespace: ingress-nginx
#   - name: infra-team-research-db-dev
#     path: infra/teams/team-research/databases/postgres-dev
#     namespace: team-research-infra
