apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-research-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements: []
  template:
    metadata:
      name: '{{team}}-{{app}}-{{env}}'
    spec:
      project: team-research
      source:
        repoURL: https://github.com/CristianHz/gitops-config.git
        targetRevision: main
        path: 'teams/{{team}}/{{app}}/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{team}}-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

# To activate, replace elements: [] with entries like:
# elements:
#   - team: team-research
#     app: react-skeleton
#     env: dev
#   - team: team-research
#     app: react-skeleton
#     env: staging
