apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: react-skeleton
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: react-skeleton
            repoURL: https://github.com/CristianHz/gitops-config.git
            targetRevision: main
            path: react-skeleton-config
            namespace: default
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
