apiVersion: platform/v1
kind: FoundryInstanceStatus
metadata:
  name: team-research-dev
spec:
  requestFile: platform/requests/foundry/team-research-dev.yaml
  team: team-research
  environment: dev
  template:
    repo: CristianHz/app-stacks
    path: templates/azure/foundry-basic
    version: v1.0.3
  azure:
    subscriptionId: 5a6786f1-b079-405d-b9cf-18cf898c60cb
    location: eastus2
    resourceGroupName: rg-chat-basic-cris02
  parameters:
    baseName: cris02
    telemetryOptOut: false
status:
  state: success
  updatedAt: 2026-07-08T17:24:37Z
  runId: "28961976228"
  runUrl: https://github.com/CristianHz/gitops-config/actions/runs/28961976228
  outputs:
    foundryName: aifcris02
    foundryProjectName: projchat
    webAppName: app-cris02
    webAppUrl: https://app-cris02-h3erepfmg3cqgucs.eastus2-01.azurewebsites.net
