apiVersion: platform/v1
kind: FoundryInstanceStatus
metadata:
  name: team-research-dev
spec:
  requestFile: platform/requests/foundry/team-research-dev.yaml
  team: team-research
  environment: dev
  template:
    repo: CristianHz/app-stacks
    path: templates/microsoft-foundry-basic
    version: v1.0.2
  azure:
    subscriptionId: 5a6786f1-b079-405d-b9cf-18cf898c60cb
    location: eastus2
    resourceGroupName: rg-chat-basic-cris01
  parameters:
    baseName: cris01
    telemetryOptOut: false
status:
  state: success
  updatedAt: 2026-07-07T20:56:14Z
  runId: "28897897915"
  runUrl: https://github.com/CristianHz/gitops-config/actions/runs/28897897915
  outputs:
    foundryName: aifcris01
    foundryProjectName: projchat
    webAppName: app-cris01
    webAppUrl: https://app-cris01-hnh2dhfuh6aagvhn.eastus2-01.azurewebsites.net
